---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone
  region: us-west-2
  version: '1.17'
  
managedNodeGroups:
  - name: capstone-ng-1
    instanceType: t3.small
    minSize: 1
    maxSize: 3
    desiredCapacity: 2 

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

