---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-cluster 
  region: us-west-2
  version: '1.17'
  
managedNodeGroups:
  - name: capstone-ng-1
    instanceType: t2.micro
    minSize: 1
    maxSize: 3
    desiredCapacity: 3

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

