apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: capstone-app
spec:
  selector:
    app: capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - name: capstone
        image: mbeimcik/capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
