apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  namespace: capstone-namespace
  labels:
    app: capstone-app
spec:
  selector:
    app: capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  namespace: capstone-namespace
  labels:
    app: capstone-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: mbeimcik/capstone
        image: capstone:latest
        ports:
        - containerPort: 80
